# Generated by Django 4.0.7 on 2022-11-19 19:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_todos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='created_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 19, 41, 29, 121757, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Photoalbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(default=datetime.datetime(2022, 11, 19, 19, 41, 29, 122758, tzinfo=utc))),
                ('img', models.FileField(blank=True, null=True, upload_to='images')),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
