# Generated by Django 4.0.7 on 2022-11-22 17:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='todos',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='created_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 17, 7, 49, 607128, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todos',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Photoalbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(default=datetime.datetime(2022, 11, 22, 17, 7, 49, 607128, tzinfo=utc))),
                ('img', models.FileField(blank=True, null=True, upload_to='images')),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
